<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE WorkFlowDefinition SYSTEM "wfdef4.dtd">
<WorkFlowDefinition ApiVersion="4.0"
Origin="JavaAPI"
	Subject="&quot;EdelweissDMS&quot;"
	Name="EdelweissDMS"
	DisableEmailNotification="false"
	MainAttachment="&quot;docAttachment&quot;"
	AuthorTool="Process Designer"
	OtherAuthorTools=""
	versionAgnostic="false"
	validateUsingSchema="true"
	validateFlag="true"
	transferFlag="true">
	<Field
		Name="Entity"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="SBU"
		Description="SBU Details"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="LOB"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="DocumentType"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Product"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Filebarcode"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Boxbarcode"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="Status"
		ValueExpr="&quot;InProgress&quot;"
		Type="string"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="Stage"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="Client"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="UniqueId"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="NoOfWorkItems"
		ValueExpr="0"
		Type="int"
		IsArray="false"
		MergeType="default"/>
	<Field
		Name="docAttachment"
		ValueExpr="&quot;||0|0||&quot;"
		Type="attachment"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="DateofArchival"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="RecordName"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="RecordClassification"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="RetentionPeriod"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="AdditionalHashtag1"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="AdditionalHashtag2"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="DMPartner"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="CapturedDate"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="RecordType"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="RecordAccess"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="ScanDate"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="TagDate"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="DispatchDate"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="override"/>
	<Map
		Name="Workflow"
		MaxStepId="92" >
		<Step
			StepId="0"
			Name="LaunchStep"
			XCoordinate="51"
			YCoordinate="93"
			RequestedInterface="Launch HTML (FileNET)"
			JoinType="none"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
			<Parameter
				Name="Product"
				ValueExpr="Product"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LOB"
				ValueExpr="LOB"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="F_Trackers"
				ValueExpr="F_Trackers"
				Type="participant"
				IsArray="true"
				Mode="inout"/>
			<Parameter
				Name="Entity"
				ValueExpr="Entity"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="DocumentType"
				ValueExpr="DocumentType"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Filebarcode"
				ValueExpr="Filebarcode"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Boxbarcode"
				ValueExpr="Boxbarcode"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="SBU"
				ValueExpr="SBU"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Stage"
				ValueExpr="Stage"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Status"
				ValueExpr="Status"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Client"
				ValueExpr="Client"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="NoOfWorkItems"
				ValueExpr="NoOfWorkItems"
				Type="int"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="docAttachment"
				ValueExpr="docAttachment"
				Type="attachment"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RetentionPeriod"
				ValueExpr="RetentionPeriod"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordType"
				ValueExpr="RecordType"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordName"
				ValueExpr="RecordName"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordClassification"
				ValueExpr="RecordClassification"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordAccess"
				ValueExpr="RecordAccess"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="DMPartner"
				ValueExpr="DMPartner"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="DateofArchival"
				ValueExpr="DateofArchival"
				Type="time"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="CapturedDate"
				ValueExpr="CapturedDate"
				Type="time"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="AdditionalHashtag2"
				ValueExpr="AdditionalHashtag2"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="AdditionalHashtag1"
				ValueExpr="AdditionalHashtag1"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="UniqueId"
				ValueExpr="UniqueId"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Route
				SourceStepId="0"
				DestinationStepId="52"
				RouteId="31">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<PostAssignments>
			<Assign LVal="UniqueId" RVal="Client+Product" />
			<Assign LVal="Status" RVal="&quot;In Progress&quot;" />
			<Assign LVal="Stage" RVal="&quot;Processing&quot;" />
			</PostAssignments>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="1"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<Step
			StepId="7"
			Name="Archival"
			XCoordinate="956"
			YCoordinate="95"
			RequestedInterface="Navigator Step Processor (default)"
			QueueName="Archiving"
			JoinType="or"
			SplitType="or"
			CanReassign="false"
			CanViewStatus="true"
			CanViewHistory="true"
			IgnoreInvalidUsers="false">
			<PreAssignments>
			<Assign LVal="Stage" RVal="&quot;Archival&quot;" />
			</PreAssignments>
			<Response Val="Archive" />
			<Parameter
				Name="Entity"
				ValueExpr="Entity"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="SBU"
				ValueExpr="SBU"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LOB"
				ValueExpr="LOB"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Product"
				ValueExpr="Product"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordName"
				ValueExpr="RecordName"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RetentionPeriod"
				ValueExpr="RetentionPeriod"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="DMPartner"
				ValueExpr="DMPartner"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Filebarcode"
				ValueExpr="Filebarcode"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Boxbarcode"
				ValueExpr="Boxbarcode"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="DateofArchival"
				ValueExpr="DateofArchival"
				Type="time"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Status"
				ValueExpr="Status"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Stage"
				ValueExpr="Stage"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Client"
				ValueExpr="Client"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="docAttachment"
				ValueExpr="docAttachment"
				Type="attachment"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordClassification"
				ValueExpr="RecordClassification"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="UniqueId"
				ValueExpr="UniqueId"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Route
				SourceStepId="7"
				DestinationStepId="49"
				RouteId="23">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<PostAssignments>
			<Assign LVal="Status" RVal="&quot;Archived&quot;" />
			</PostAssignments>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="2"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<CompoundStep
			StepId="22"
			Name="TerminateProcess"
			XCoordinate="880"
			YCoordinate="262"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="23"
				Action="terminateProcess">
			</Instruction>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_IconName"
					Type="string"
					IsArray="false">
						<Value Val="filenet/vw/toolkit/utils/images/terminate_process_step"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="6"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StartIconName"
					Type="string"
					IsArray="false">
						<Value Val="filenet/vw/toolkit/utils/images/start_terminate_process_step"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StepPropertiesPanelClass"
					Type="string"
					IsArray="false">
						<Value Val="filenet.vw.toolkit.design.property.steps.systeminstructions.VWTerminateProcessPropertiesPanel"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<CompoundStep
			StepId="28"
			Name="UpdateDocumentProperties"
			XCoordinate="826"
			YCoordinate="95"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="91"
				Action="execute">
				<Expression Val="UpdateDocumentProperties" />
				<Expression Val="UpdateDispatchedDate" />
				<Expression Val="DispatchDate" />
				<Expression Val="docAttachment" />
			</Instruction>
			<Route
				SourceStepId="28"
				DestinationStepId="7"
				RouteId="22">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="8"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<Step
			StepId="34"
			Name="Dispatch"
			XCoordinate="621"
			YCoordinate="94"
			RequestedInterface="Navigator Step Processor (default)"
			QueueName="Archiving"
			JoinType="or"
			SplitType="or"
			CanReassign="false"
			CanViewStatus="true"
			CanViewHistory="true"
			IgnoreInvalidUsers="false">
			<PreAssignments>
			<Assign LVal="Stage" RVal="&quot;Archival&quot;" />
			</PreAssignments>
			<Response Val="Dispatch" />
			<Parameter
				Name="Entity"
				ValueExpr="Entity"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="SBU"
				ValueExpr="SBU"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LOB"
				ValueExpr="LOB"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Product"
				ValueExpr="Product"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordName"
				ValueExpr="RecordName"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RetentionPeriod"
				ValueExpr="RetentionPeriod"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="DMPartner"
				ValueExpr="DMPartner"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Filebarcode"
				ValueExpr="Filebarcode"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Boxbarcode"
				ValueExpr="Boxbarcode"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Status"
				ValueExpr="Status"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Stage"
				ValueExpr="Stage"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Client"
				ValueExpr="Client"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="docAttachment"
				ValueExpr="docAttachment"
				Type="attachment"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordClassification"
				ValueExpr="RecordClassification"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="UniqueId"
				ValueExpr="UniqueId"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Route
				SourceStepId="34"
				DestinationStepId="46"
				RouteId="20">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<PostAssignments>
			<Assign LVal="Status" RVal="&quot;Dispatched&quot;" />
			<Assign LVal="DispatchDate" RVal="systemtime()" />
			</PostAssignments>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="2"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<CompoundStep
			StepId="46"
			Name="Update Status"
			XCoordinate="729"
			YCoordinate="94"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="47"
				Action="call">
				<Expression Val="UpdateDocSattus" />
			</Instruction>
			<Route
				SourceStepId="46"
				DestinationStepId="28"
				RouteId="21">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="4"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<CompoundStep
			StepId="49"
			Name="Update Status"
			XCoordinate="1117"
			YCoordinate="95"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="50"
				Action="call">
				<Expression Val="UpdateDocSattus" />
			</Instruction>
			<Route
				SourceStepId="49"
				DestinationStepId="89"
				RouteId="43"/>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="4"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<CompoundStep
			StepId="52"
			Name="Component"
			XCoordinate="148"
			YCoordinate="93"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="71"
				Action="execute">
				<Expression Val="WorkFlowUpdateComponent" />
				<Expression Val="DocumentStringPropertyUpdate" />
				<Expression Val="docAttachment" />
				<Expression Val="&quot;UniqueId&quot;" />
				<Expression Val="UniqueId" />
			</Instruction>
			<Instruction
				Id="92"
				Action="execute">
				<Expression Val="WorkFlowUpdateComponent" />
				<Expression Val="updateSecurityProxy" />
				<Expression Val="docAttachment" />
			</Instruction>
			<Instruction
				Id="73"
				Action="execute">
				<Expression Val="WorkFlowUpdateComponent" />
				<Expression Val="edelCreateDocument1" />
				<Expression Val="docAttachment" />
				<Expression Val="F_WorkFlowNumber" />
				<Expression Val="NoOfWorkItems" />
			</Instruction>
			<Route
				SourceStepId="52"
				DestinationStepId="22"
				RouteId="34"
				Condition="NoOfWorkItems &gt; 1">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="50"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<Route
				SourceStepId="52"
				DestinationStepId="76"
				RouteId="36">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="50"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="8"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<CompoundStep
			StepId="59"
			Name="Update Status"
			XCoordinate="493"
			YCoordinate="93"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="60"
				Action="call">
				<Expression Val="UpdateDocSattus" />
			</Instruction>
			<Route
				SourceStepId="59"
				DestinationStepId="34"
				RouteId="30">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="4"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<Step
			StepId="75"
			Name="Processing"
			XCoordinate="340"
			YCoordinate="93"
			RequestedInterface="Navigator Step Processor (default)"
			QueueName="ScanningQA"
			JoinType="or"
			SplitType="or"
			CanReassign="false"
			CanViewStatus="true"
			CanViewHistory="true"
			IgnoreInvalidUsers="false">
			<Response Val="Processing Complete" />
			<Parameter
				Name="Entity"
				ValueExpr="Entity"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="SBU"
				ValueExpr="SBU"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LOB"
				ValueExpr="LOB"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Product"
				ValueExpr="Product"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordName"
				ValueExpr="RecordName"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RetentionPeriod"
				ValueExpr="RetentionPeriod"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="DMPartner"
				ValueExpr="DMPartner"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Status"
				ValueExpr="Status"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Stage"
				ValueExpr="Stage"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Client"
				ValueExpr="Client"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="docAttachment"
				ValueExpr="docAttachment"
				Type="attachment"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="RecordClassification"
				ValueExpr="RecordClassification"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="UniqueId"
				ValueExpr="UniqueId"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Route
				SourceStepId="75"
				DestinationStepId="59"
				RouteId="41">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<PostAssignments>
			<Assign LVal="Status" RVal="&quot;Pending for dispatch&quot;" />
			</PostAssignments>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="2"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<CompoundStep
			StepId="76"
			Name="Update Status"
			XCoordinate="244"
			YCoordinate="93"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="77"
				Action="call">
				<Expression Val="UpdateDocSattus" />
			</Instruction>
			<Route
				SourceStepId="76"
				DestinationStepId="75"
				RouteId="35">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="4"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<CompoundStep
			StepId="89"
			Name="Update Archival Date"
			XCoordinate="1033"
			YCoordinate="189"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="90"
				Action="execute">
				<Expression Val="UpdateArchivalDateInContentEngine" />
				<Expression Val="UpdateArchivalDate" />
				<Expression Val="DateofArchival" />
				<Expression Val="docAttachment" />
			</Instruction>
			<Route
				SourceStepId="89"
				DestinationStepId="22"
				RouteId="42">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="8"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
	</Map>
	<Map
		Name="UpdateDocSattus"
		MaxStepId="87"
		Description="" >
		<Step
			StepId="0"
			Name="StartStep"
			XCoordinate="43"
			YCoordinate="96"
			RequestedInterface="Navigator Step Processor (default)"
			Deadline="0"
			Reminder="0"
			JoinType="or"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
			<Route
				SourceStepId="0"
				DestinationStepId="7"
				RouteId="0">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="50"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<Route
				SourceStepId="0"
				DestinationStepId="16"
				RouteId="2">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="50"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="3"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<CompoundStep
			StepId="7"
			Name="Status Component"
			XCoordinate="218"
			YCoordinate="20"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="19"
				Action="execute">
				<Expression Val="WorkFlowUpdateComponent" />
				<Expression Val="DocumentStringPropertyUpdate" />
				<Expression Val="docAttachment" />
				<Expression Val="&apos;Status&apos;" />
				<Expression Val="Status" />
			</Instruction>
			<Instruction
				Id="20"
				Action="execute">
				<Expression Val="WorkFlowUpdateComponent" />
				<Expression Val="DocumentStringPropertyUpdate" />
				<Expression Val="docAttachment" />
				<Expression Val="&apos;Stage&apos;" />
				<Expression Val="Stage" />
			</Instruction>
			<Instruction
				Id="21"
				Action="execute">
				<Expression Val="WorkFlowUpdateComponent" />
				<Expression Val="DocumentStringPropertyUpdate" />
				<Expression Val="docAttachment" />
				<Expression Val="&apos;BoxBarcode&apos;" />
				<Expression Val="Boxbarcode" />
			</Instruction>
			<Instruction
				Id="22"
				Action="execute">
				<Expression Val="WorkFlowUpdateComponent" />
				<Expression Val="DocumentStringPropertyUpdate" />
				<Expression Val="docAttachment" />
				<Expression Val="&apos;FileBarcode&apos;" />
				<Expression Val="Filebarcode" />
			</Instruction>
			<Route
				SourceStepId="7"
				DestinationStepId="16"
				RouteId="8">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="8"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
		<CompoundStep
			StepId="16"
			Name="Return"
			XCoordinate="404"
			YCoordinate="97"
			JoinType="or"
			SplitType="or">
			<Instruction
				Id="17"
				Action="return">
				<Expression Val="false" />
			</Instruction>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_IconName"
					Type="string"
					IsArray="false">
						<Value Val="filenet/vw/toolkit/utils/images/return_step"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="6"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StartIconName"
					Type="string"
					IsArray="false">
						<Value Val="filenet/vw/toolkit/utils/images/start_return_step"/>
				</ModelAttribute>
				<ModelAttribute
					Name="UI_StepPropertiesPanelClass"
					Type="string"
					IsArray="false">
						<Value Val="filenet.vw.toolkit.design.property.steps.systeminstructions.VWReturnPropertiesPanel"/>
				</ModelAttribute>
			</ModelAttributes>
		</CompoundStep>
	</Map>
</WorkFlowDefinition>
